### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by AsheshPlays** [teach310/AssetBundleHub#13]
Hello! I am looking for an Assetbundle that is similar to OxGFrame that uses XOR or AES. And easy to use. Is this repo ready to use?

**Comment by teach310** [comment]
@AsheshPlays 
Hello! 

> Is this repo ready to use?

This repo is stil alpha. 
This tool already can download, load, build and simple XOR encryption.

But, I don't recommend you to use this tool yet. ( Until release version 1.0.0)
Because I will develop with many Breaking Changes.

**Comment by AsheshPlays** [comment]
Ok. I will wait for the release version.
